accepted = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
]
no-clearly-defined = true

[unicode-ident]
accepted = ["Unicode-DFS-2016"]

[hifitime]
accepted = ["MPL-2.0"]
