[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
]

exceptions = [
    # MPL-2.0 is a copyleft license, but we can still fulfill its requirements if:
    # - We include a copyright notice (which we do through `THIRD_PARTY_LICENSES.md`)
    # - We include the full license (which we do through `THIRD_PARTY_LICENSES.md`)
    # - We disclose source-code (which we do, since this tool is open-source)
    # - We include instructions to obtain the source (which we do through `THIRD_PARTY_LICENSES.md`)
    { allow = ["MPL-2.0"], crate = "hifitime"},
]

[bans]
wildcards = "deny"
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

unknown-git = "deny"
allow-git = []
